export default
[
    { id: 1, icon: 'fa-couch', description: 'Sofa' },
    { id: 2, icon: 'fa-chair', description: 'Chair' },
    { id: 3, icon: 'fa-table', description: 'Table' },
    { id: 4, icon: 'fa-bed', description: 'Bed' },
    { id: 5, icon: 'fa-desktop', description: 'Desk' },
    { id: 6, icon: 'fa-chess-bishop', description: 'Bench' },
    { id: 7, icon: 'fa-cube', description: 'Stool' },
    { id: 8, icon: 'fa-layer-group', description: 'Shelf' },
    { id: 9, icon: 'fa-couch', description: 'Couch' },
    { id: 10, icon: 'fa-box', description: 'Cabinets' },
    { id: 11, icon: 'fa-cube', description: 'Ottoman' },
    { id: 12, icon: 'fa-warehouse', description: 'Wardrobe' },
    { id: 13, icon: 'fa-draw-polygon', description: 'Dresser' },
    { id: 14, icon: 'fa-door-closed', description: 'Closet' },
    { id: 15, icon: 'fa-square', description: 'Mirror' },
    { id: 16, icon: 'fa-boxes', description: 'Drawer' },
    { id: 17, icon: 'fa-tv', description: 'TV Unit' },
    { id: 18, icon: 'fa-stop', description: 'Stand' },
    { id: 19, icon: 'fa-border-all', description: 'Rug' },
    { id: 20, icon: 'fa-grip-lines', description: 'Mat' },
    { id: 21, icon: 'fa-lightbulb', description: 'Lamp' },
    { id: 22, icon: 'fa-swatchbook', description: 'Swing' },
    { id: 23, icon: 'fa-baby', description: 'Crib' },
    { id: 24, icon: 'fa-layer-group', description: 'Bunks' },
    { id: 25, icon: 'fa-stream', description: 'Rack' },
    { id: 26, icon: 'fa-bed', description: 'Divan' },
    { id: 27, icon: 'fa-circle', description: 'Pouffe' },
    { id: 28, icon: 'fa-couch', description: 'Settee' },
    { id: 29, icon: 'fa-lock', description: 'Locker' },
    { id: 30, icon: 'fa-archive', description: 'Chests' }
      
    ]
